language: node_js
node_js:
    - '12.16.3'
cache: yarn
script:
    - echo 'Build starts!!'
    - echo 'Installing Deps!'
    - yarn
    - echo 'Testing!'
    - yarn test
after_success:
    - ./travis-merge.sh
